### ISSUE TITLE
ADAFRUIT METRO M4 EXPRESS AIRLIFT (WIFI) - LITE problems

### ISSUE THREAD

**Issue by budgey** [khoih-prog/EthernetWebServer#10]
Hi,
Having issues with metro m4 airlift. I have tried w5100 and w5500 and ethernet, ethernet2, ethernet3 libraries and I always get 0.0.0.0

Starting WebServer on SAMD51 ADAFRUIT_METRO_M4_AIRLIFT_LITE with W5x00 using Ethernet Library
[ETHERNET_WEBSERVER] =========== USE_ETHERNET ===========
[ETHERNET_WEBSERVER] Default SPI pinout:
[ETHERNET_WEBSERVER] MOSI: 26
[ETHERNET_WEBSERVER] MISO: 24
[ETHERNET_WEBSERVER] SCK: 25
[ETHERNET_WEBSERVER] SS: 36
[ETHERNET_WEBSERVER] =========================
[ETHERNET_WEBSERVER] Board : SAMD51 ADAFRUIT_METRO_M4_AIRLIFT_LITE , setCsPin: 10

Currently Used SPI pinout:
MOSI:26
MISO:24
SCK:25
SS:36

Using mac index = 3
EthernetWebServer started @ IP address: 0.0.0.0

**Comment by khoih-prog** [comment]
That happens when the M4 board **couldn't communicate to the W5x00 via SPI bus, then couldn't initialize the W5x00.** You must have the wiring connected not correctly.

There are something you need to check

1. Did you modify the Ethernet libraries according to [**Libraries' Patches**](https://github.com/khoih-prog/EthernetWebServer#libraries-patches)?
2. Did you check, recheck and verify the pins and connection from the W5x00 to Metro M4 Airlift? Please be sure you have connected to the **SPI ICSP header on the right side of the board** (MOSI/MISO/SCK) and **pin 10 for CS** for W5x00.

![image](https://user-images.githubusercontent.com/57012152/97099418-12ea9600-165f-11eb-9bb4-ee8247e64db7.png)

If you still have issue, it's easier for you to use the W5100 shield with ICSP connector + Ethernet/EthernetLarge Library

![w5100-ethernet-shield-suf-3](https://user-images.githubusercontent.com/57012152/97099512-28ac8b00-1660-11eb-977f-9bd0e319f965.jpg)
