### ISSUE TITLE
Arduino Mega not work pin SS

### ISSUE THREAD

**Issue by BorgMcz** [khoih-prog/EthernetWebServer#4]
Good day,

if I use Arduino Mega output number 53 for SS pin, wiznet 5500 is not functional. If I use pin 10 Arduino, everything works.

Used standard ethernet library in version 2.0.0.

**Comment by khoih-prog** [comment]
Dear @BorgMcz 

The EthernetWebServer **depends on many other libraries**, such as Ethernet, Ethernet2, etc. and can not do the work alone if there is bug or connection is not correct or a new variation of board is used.

The best way to solve a similar issue is to run a simple example from the underlying libraries (Ethernet, Ethernet2, etc. )  to verify if the pin usage is working before using the higher level of libraries, such as EthernetWebServer.

If you still have the problem with the underlying libraries, it's better to open an issue there so that the issue could be solved completely at the correct place.

I still can investigate later, if the problem can be solved, can just provide you a quick-fixing kludge / patch for the library.

But as you known, **W5x00 CS/SS normally is pin 10**, and some Mega  / SAM DUE boards have the internal SPI bus pins assigned to pins 50, 51, 52, 53 or the ICSP connector so that W5100 can be used more easily.

Thanks for your sharing of experience.

Regards,
